export default {
  directions: {
    NORTH: 'NORTH',
    EAST: 'EAST',
    WEST: 'WEST',
    SOUTH: 'SOUTH',
  },
  dimensions: {
    X_MIN: 0,
    Y_MIN: 0,
    X_MAX: 5,
    Y_MAX: 5,
  },
  validCommands: [
    'PLACE',
    'LEFT',
    'RIGHT',
    'MOVE',
    'REPORT'
  ],
  validationMessages: {
    X_NOT_NUMBER: 'X VALUE SHOULD BE A NUMBER',
    X_LIMIT: 'X POSITION CROSSES THE SPECIFIED LIMIT',
    Y_NOT_NUMBER: 'Y VALUE SHOULD BE A NUMBER',
    Y_LIMIT: 'Y POSITION CROSSES THE SPECIFIED LIMIT',
    INVALID_DIRECTION: 'INVALID DIRECTION VALUE',
    INVALID_PLACEMENT: 'TOY NEEDS TO BE PLACED FIRST',
    INVALID_PLACE_COMMAND: 'PLACE CMD NEEDS PARAMETERS',
    INVALID_PLACE_PARAMS: 'PLACE CMD NEEDS 3 PARAMETERS: X,Y,F',
  }
};
